//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.erpPlatform {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.bedp.byttersoft.com", ConfigurationName="erpPlatform.erpPlatformPortType")]
    public interface erpPlatformPortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:serverErpXml", ReplyAction="urn:serverErpXmlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp2.erpPlatform.serverErpXmlResponse serverErpXml(WindowsFormsApp2.erpPlatform.serverErpXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serverErpXml", WrapperNamespace="http://webservice.bedp.byttersoft.com", IsWrapped=true)]
    public partial class serverErpXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.bedp.byttersoft.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string erpReqXml;
        
        public serverErpXmlRequest() {
        }
        
        public serverErpXmlRequest(string erpReqXml) {
            this.erpReqXml = erpReqXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serverErpXmlResponse", WrapperNamespace="http://webservice.bedp.byttersoft.com", IsWrapped=true)]
    public partial class serverErpXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.bedp.byttersoft.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public serverErpXmlResponse() {
        }
        
        public serverErpXmlResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface erpPlatformPortTypeChannel : WindowsFormsApp2.erpPlatform.erpPlatformPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class erpPlatformPortTypeClient : System.ServiceModel.ClientBase<WindowsFormsApp2.erpPlatform.erpPlatformPortType>, WindowsFormsApp2.erpPlatform.erpPlatformPortType {
        
        public erpPlatformPortTypeClient() {
        }
        
        public erpPlatformPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public erpPlatformPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public erpPlatformPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public erpPlatformPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.erpPlatform.serverErpXmlResponse WindowsFormsApp2.erpPlatform.erpPlatformPortType.serverErpXml(WindowsFormsApp2.erpPlatform.serverErpXmlRequest request) {
            return base.Channel.serverErpXml(request);
        }
        
        public string serverErpXml(string erpReqXml) {
            WindowsFormsApp2.erpPlatform.serverErpXmlRequest inValue = new WindowsFormsApp2.erpPlatform.serverErpXmlRequest();
            inValue.erpReqXml = erpReqXml;
            WindowsFormsApp2.erpPlatform.serverErpXmlResponse retVal = ((WindowsFormsApp2.erpPlatform.erpPlatformPortType)(this)).serverErpXml(inValue);
            return retVal.@return;
        }
    }
}
